### ISSUE TITLE
[BUG]: Cannot find package 'typescript' when running in environments without explicit TS dependency like Bun

### ISSUE THREAD

**Issue by 0xMurage** [RobinBlomberg/kysely-codegen#318]
**Description**

The library currently imports the typescript package directly in the type expression parser https://github.com/RobinBlomberg/kysely-codegen/blob/dacb4faaec98061a1946ffac96347b9d5f4fb63d/src/generator/parser/type-expression-parser.ts#L1 

However, typescript is **not** listed as a production dependency (or peerDependency) in [package.json](https://github.com/RobinBlomberg/kysely-codegen/blob/dacb4faaec98061a1946ffac96347b9d5f4fb63d/package.json#L49-L58).

While this usually goes unnoticed in most setups because devs typically have typescript installed as a dependency in their own project, it causes a runtime crash in other environments.

 For example, when using the Bun runtime which handles TypeScript transpilation natively,  kysely-codegen fails immediately with 
 `error: Cannot find package 'typescript' from '......../node_modules/kysely-codegen/dist/generator/parser/type-expression-parser.js'

**Steps to Reproduce**

1. Create a fresh project using Bun (without installing the `typescript` npm package).
2. Install `kysely-codegen`.
3. Attempt to run the codegen CLI.
4. The execution will fail with the missing package error.

**Suggested Solution**
Move current `typescript` devDependency  to a formal dependency or peer dependency in package.json.

**Comment by daviduzumeri** [comment]
Worth noting this _also_ happens when using TypeScript 7 RC, which may be an even bigger issue. It might be wise to swap the dep to `@typescript/typescript6`.

**Comment by ismailkarsli** [comment]
Currently using this workaround to make kysely-codegen work with TypeScript 7:

```js
// .pnpmfile.mjs

function readPackage(pkg, context) {
	// cosmiconfig (used by kysely-codegen) uses TypeScript internals
	// (findConfigFile) that were removed in TypeScript 7.
	// Remove the typescript peer dep and add it as a direct dep on v6 instead.
	if (pkg.name === "cosmiconfig") {
		if (pkg.peerDependencies?.typescript) {
			delete pkg.peerDependencies.typescript;
		}
		if (pkg.peerDependenciesMeta?.typescript) {
			delete pkg.peerDependenciesMeta.typescript;
		}
		pkg.dependencies = {
			...pkg.dependencies,
			typescript: "^6.0.0",
		};
		context.log("cosmiconfig: added direct dep on ^6.0.0");
	}
	return pkg;
}

export const hooks = { readPackage };
```

I think the similar approach would work with Bun.

**Comment by 0xMurage** [comment]
I just created a fresh project with TypeScript 7.0.2 (was released a few hours ago) and the codegen ran successfully.

@ismailkarsli It won't work with the release candidate (7.0.1-rc), so I suggest upgrading rather than using your hack.

**Comment by ismailkarsli** [comment]
> I just created a fresh project with TypeScript 7.0.2 (was released a few hours ago) and the codegen ran successfully.
> 
> [@ismailkarsli](https://github.com/ismailkarsli) It won't work with the release candidate (7.0.1-rc), so I suggest upgrading rather than using your hack.

I am using a specific case where I produce both TypeScript and Zod output using custom serializer so unfortunately even stable 7.0.2 is not working for me.

Edit:
This one is much easier fix:
```yaml
# pnpm-workspace.yaml
packageExtensions:
  kysely-codegen:
    dependencies:
      typescript: 6.0.3
```

**Comment by rh-asterkho** [comment]
@0xMurage it crashes for me with typescript 7.0.2: `typescript.findConfigFile is not a function`

**Comment by vjpr** [comment]
Same with pnpm + https://pnpm.io/global-virtual-store.

```
error: Cannot find package 'typescript' from '/xxx/Library/pnpm/store/v11/links/@/kysely-codegen/0.20.0/a5adbcbb3db1db7c53d08ce6735ca7436989e1de64619214dc3edaf0789ca278/node_modules/kysely-codegen/dist/generator/parser/type-expression-parser.js'
```
